name: Read_test_on_push
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.Opcua.Read/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Opcua.Read
      dotnet_version: 8.0.x
      strict_analyzers: true
      prebuild_command: "cd Frends.Opcua.Read.Tests && chmod 777 ./generate-certs.sh && ./generate-certs.sh && docker-compose up -d && sleep 60"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
